name: Baseline JS-03
on:
  workflow_dispatch:
jobs:
  run-scenario:
    uses: ./.github/workflows/templates/baseline-npm-remediation.yml
    with:
      profile: profiles/JS-03.yaml
    secrets: inherit
