name: Baseline JS-06
on:
  workflow_dispatch:
jobs:
  run-scenario:
    uses: ./.github/workflows/templates/baseline-npm-remediation.yml
    with:
      profile: profiles/JS-06.yaml
    secrets: inherit
