name: Baseline AF-05
on:
  workflow_dispatch:
jobs:
  run-scenario:
    uses: ./.github/workflows/templates/baseline-python-remediation.yml
    with:
      profile: profiles/AF-05.yaml
    secrets: inherit
